version: 0.2 
phases:
  install:
    runtime-versions:
      java : corretto17
  pre_build:
    commands:
      - echo "pre-build started"
      - pwd
      - ls -lrta
     #- echo "code scan using sonarqube"
     #- mvn verify sonar:sonar
     #- echo "code scan has been completed"
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -lrta
      - cp -pvr settings.xml /root/.m2/
      #- mvn clean validate compile test verify package install deploy
      - mvn deploy
      - ls -lrta
      - echo "Artifact has been uploaded to JFrog!"

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
